### PR TITLE
Update version information in setup.py

### PR DESCRIPTION
**Pull request by acesnik**

### CODE REVIEW

**Comment by gfacciol** [comment]
I don't see the point of changing the version number.

**Comment by acesnik** [comment]
Just made the PR because the version reported by the tool didn't match the version on pypi: https://pypi.org/project/pypotree/

-AC

image

**Comment by gfacciol** [comment]
Thanks! If you reopen the PR I will merge.

**Comment by acesnik** [comment]
I don't have permissions to reopen this one, so here's a new one with the same version change: 
https://github.com/centreborelli/pypotree/pull/6

**Pull request closed without merging**
